ggssl.lo: /home/sk/GoGetSSL/PHP-CSR-Decoder/ggssl.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/sk/GoGetSSL/PHP-CSR-Decoder $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/sk/GoGetSSL/PHP-CSR-Decoder/ggssl.c -o ggssl.lo 
$(phplibdir)/ggssl.la: ./ggssl.la
	$(LIBTOOL) --mode=install cp ./ggssl.la $(phplibdir)

./ggssl.la: $(shared_objects_ggssl) $(GGSSL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_ggssl) $(GGSSL_SHARED_LIBADD)

